[project]
name = "speedup"
version = "0.0.0"

[build-system]
requires = ["maturin<2.0"]
build-backend = "maturin"

[tool.maturin]
bindings = "pyo3"
features = ["pyo3/extension-module"]
module-name = "speedup"
profile = "release"
editable-profile = "release"
