[aeroway]
aerodrome = "_generated/aeroway_airport.webp"
gate = "_generated/aeroway_gate.webp"
helipad = "_generated/aeroway_helipad.webp"
parking_position = "_generated/aeroway_gate.webp"
terminal = "_generated/aeroway_terminal.webp"

["aeroway.way"]
runway = "_generated/aeroway_runway.webp"
taxiway = "_generated/aeroway_taxiway.webp"

[amenity]
atm = "_generated/amenity_atm2.webp"
bank = "_generated/amenity_bank2.webp"
bar = "_generated/amenity_bar2.webp"
bench = "_generated/amenity_bench2.webp"
bicycle_parking = "_generated/amenity_bicycle_parking.webp"
bicycle_rental = "_generated/amenity_bicycle_rental.webp"
biergarten = "_generated/amenity_biergarten.webp"
bureau_de_change = "_generated/amenity_bureau_de_change.webp"
bus_station = "_generated/amenity_bus_station2.webp"
cafe = "_generated/amenity_cafe2.webp"
car_rental = "_generated/amenity_car_rental.webp"
car_sharing = "_generated/amenity_car_sharing.webp"
# TODO: car_wash
casino = "_generated/amenity_casino.webp"
# TODO: charging_station
childcare = "_generated/amenity_nursery.webp"
cinema = "_generated/amenity_cinema2.webp"
clinic = "_generated/amenity_doctors.webp"
clock = "_generated/amenity_clock.webp"
college = "_generated/amenity_college.webp"
courthouse = "_generated/amenity_courthouse2.webp"
dentist = "_generated/amenity_dentist2.webp"
doctors = "_generated/amenity_doctors2.webp"
drinking_water = "_generated/amenity_drinking_water2.webp"
fast_food = "_generated/amenity_fast_food2.webp"
fire_station = "_generated/amenity_fire_station2.webp"
fountain = "_generated/amenity_fountain.webp"
fuel = "_generated/amenity_fuel2.webp"
grave_yard = "_generated/historic_memorial2.webp"
hospital = "_generated/amenity_hospital2.webp"
hunting_stand = "_generated/man_made_lookout_tower.webp"
ice_cream = "_generated/amenity_ice_cream.webp"
kindergarten = "_generated/amenity_school.webp"
library = "_generated/amenity_library2.webp"
luggage_locker = "_generated/amenity_luggage_locker.webp"
marketplace = "_generated/amenity_marketplace.webp"
nightclub = "_generated/amenity_nightclub.webp"
parking = "_generated/amenity_parking.webp"
# TODO: parking_entrance
# TODO: parking_space
pharmacy = "_generated/amenity_pharmacy2.webp"
photo_booth = "_generated/amenity_photo_booth.webp"
place_of_worship = "_generated/amenity_place_of_worship.webp"
police = "_generated/amenity_police2.webp"
post_box = "_generated/amenity_post_box.webp"
post_office = "_generated/amenity_post_office.webp"
prison = "_generated/amenity_prison2.webp"
pub = "_generated/amenity_pub2.webp"
public_building = "_generated/amenity_public_building.webp"
recycling = "_generated/amenity_recycling2.webp"
restaurant = "_generated/amenity_restaurant2.webp"
school = "_generated/amenity_school.webp"
shelter = "_generated/amenity_shelter2.webp"
stripclub = "_generated/amenity_nightclub.webp"
taxi = "_generated/amenity_taxi2.webp"
telephone = "_generated/amenity_telephone.webp"
theatre = "_generated/amenity_theatre2.webp"
toilets = "_generated/amenity_toilets2.webp"
townhall = "_generated/amenity_townhall2.webp"
university = "_generated/amenity_university.webp"
vending_machine = "_generated/amenity_vending_machine.webp"
veterinary = "_generated/amenity_veterinary.webp"
waste_basket = "_generated/amenity_waste_basket2.webp"
water_point = "_generated/amenity_drinking_water2.webp"

[barrier]
block = "_generated/barrier_block.webp"
bollard = "_generated/barrier_bollard.webp"
cattle_grid = "_generated/barrier_cattle_grid.webp"
cycle_barrier = "_generated/barrier_cycle_barrier.webp"
entrance = "_generated/barrier_entrance.webp"
gate = "_generated/barrier_gate2.webp"
# TODO: kerb
kissing_gate = "_generated/barrier_kissing_gate.webp"
lift_gate = "_generated/barrier_lift_gate.webp"
stile = "_generated/barrier_stile.webp"
toll_booth = "_generated/barrier_toll_booth.webp"
turnstile = "_generated/barrier_turnstile.webp"

["barrier.way"]
fence = "_generated/barrier_wall.webp"
# TODO: hedge
wall = "_generated/barrier_wall.webp"

[boundary]
"*" = "_generated/iD/boundary.webp"

[building]
bunker = "_generated/military_bunker.webp"

["building.way"]
"*" = "_generated/building.webp"

[crab]
yes = "crab_yes.webp"  # don't spoil it :-)

[diplomatic]
embassy = "_generated/diplomatic_embassy.webp"

[emergency]
assembly_point = "_generated/emergency_assembly_point.webp"
defibrillator = "_generated/emergency_defibrillator.webp"
fire_extinguisher = "_generated/emergency_fire_extinguisher.webp"
fire_hose = "_generated/emergency_fire_hose.webp"
fire_hydrant = "_generated/emergency_fire_hydrant.webp"
phone = "_generated/emergency_phone.webp"
siren = "_generated/emergency_siren.webp"

[ford]
"*" = "_generated/ford_yes.webp"

[highway]
bus_stop = "_generated/highway_bus_stop2.webp"
crossing = "_generated/highway_crossing_zebra.webp"
elevator = "_generated/passage_elevator.webp"
mini_roundabout = "_generated/highway_mini_roundabout.webp"
passing_place = "_generated/mountain_pass.webp"
# TODO: speed_camera
street_lamp = "_generated/man_made_lamp.webp"
traffic_signals = "_generated/highway_traffic_signals2.webp"
turning_circle = "_generated/highway_turning_circle2.webp"
turning_loop = "_generated/highway_turning_circle2.webp"

["highway.way"]
bridleway = "_generated/highway_bridleway.webp"
cycleway = "_generated/highway_cycleway.webp"
footway = "_generated/highway_footway.webp"
living_street = "_generated/highway_service.webp"
motorway = "_generated/highway_motorway.webp"
motorway_link = "_generated/highway_motorway.webp"
path = "_generated/highway_path.webp"
pedestrian = "_generated/highway_service.webp"
primary = "_generated/highway_primary.webp"
primary_link = "_generated/highway_primary.webp"
residential = "_generated/highway_unclassified.webp"
secondary = "_generated/highway_secondary.webp"
secondary_link = "_generated/highway_secondary.webp"
service = "_generated/highway_service.webp"
steps = "_generated/highway_steps.webp"
tertiary = "_generated/highway_tertiary.webp"
track = "_generated/highway_track.webp"
trunk = "_generated/highway_trunk.webp"
trunk_link = "_generated/highway_trunk.webp"
unclassified = "_generated/highway_unclassified.webp"

[historic]
archaeological_site = "_generated/historic_archaeological_site2.webp"
castle = "_generated/historic_castle.webp"
memorial = "_generated/historic_memorial2.webp"
mine = "_generated/historic_mine.webp"
monument = "_generated/historic_monument2.webp"
ruins = "_generated/historic_ruins.webp"
tomb = "_generated/historic_memorial2.webp"
wayside_cross = "_generated/historic_wayside_cross.webp"
wayside_shrine = "_generated/historic_wayside_shrine.webp"
wreck = "_generated/historic_wreck.webp"

["industrial.way"]
port = "_generated/industrial_port.webp"

["landuse.way"]
allotments = "_generated/landuse_allotments.webp"
basin = "_generated/waterway_lake.webp"
brownfield = "_generated/landuse_brownfield.webp"
cemetery = "_generated/landuse_cemetery.webp"
commercial = "_generated/landuse_commercial.webp"
farmland = "_generated/landuse_farmland.webp"
farmyard = "_generated/landuse_farmyard.webp"
forest = "_generated/landuse_forest.webp"
grass = "_generated/landuse_grass2.webp"
industrial = "_generated/landuse_industrial.webp"
meadow = "_generated/landuse_meadow.webp"
military = "_generated/landuse_military.webp"
# TODO: orchard
quarry = "_generated/landuse_quarry.webp"
recreation_ground = "_generated/leisure_sports_centre.webp"
reservoir = "_generated/waterway_lake.webp"
residential = "_generated/landuse_residential.webp"
retail = "_generated/landuse_retail.webp"
tourism = "_generated/landuse_tourism.webp"
village_green = "_generated/landuse_grass2.webp"
# TODO: vineyard

[leisure]
marina = "_generated/leisure_marina.webp"
slipway = "_generated/leisure_slipway.webp"

["leisure.way"]
garden = "_generated/landuse_grass2.webp"
golf_course = "_generated/leisure_golf_course.webp"
nature_reserve = "_generated/leisure_natural_reserve.webp"
park = "_generated/leisure_park.webp"
pitch = "_generated/leisure_pitch.webp"
playground = "_generated/leisure_playground2.webp"
sports_centre = "_generated/leisure_sports_centre.webp"
swimming_pool = "_generated/waterway_lake.webp"
water_park = "_generated/leisure_water_park.webp"

[man_made]
crane = "_generated/man_made_crane.webp"
lighthouse = "_generated/man_made_lighthouse2.webp"
mast = "_generated/man_made_communications_tower.webp"
pipeline = "_generated/iD/pipeline-line.webp"
storage_tank = "_generated/man_made_water_tower.webp"
surveillance = "_generated/man_made_surveillance.webp"
survey_point = "_generated/man_made_survey_point.webp"
tower = "_generated/man_made_lookout_tower.webp"
utility_pole = "_generated/power_pole.webp"
water_tower = "_generated/man_made_water_tower2.webp"
windmill = "_generated/man_made_windmill2.webp"

["man_made.way"]
bridge = "_generated/man_made_bridge.webp"
tunnel = "_generated/man_made_tunnel.webp"

[military]
bunker = "_generated/military_bunker.webp"

[natural]
cave_entrance = "_generated/natural_cave_entrance.webp"
peak = "_generated/natural_peak.webp"
tree = "_generated/natural_tree.webp"

["natural.way"]
grassland = "_generated/natural_grassland.webp"
heath = "_generated/natural_heath.webp"
scrub = "_generated/natural_scrub.webp"
water = "_generated/waterway_lake.webp"
wood = "_generated/natural_wood.webp"

[place]
"*" = "_generated/place_town.webp"

["plant:method"]
combustion = "_generated/power_plant_coal.webp"
photovoltaic = "_generated/power_plant_photovoltaic.webp"
run-of-the-river = "_generated/power_plant_hydro.webp"
water-pumped-storage = "_generated/power_plant_hydro.webp"
water-storage = "_generated/power_plant_hydro.webp"
wind_turbine = "_generated/power_plant_wind.webp"

[power]
pole = "_generated/power_pole.webp"
substation = "_generated/power_substation.webp"
tower = "_generated/power_tower.webp"
transformer = "_generated/power_transformer.webp"

[railway]
halt = "_generated/railway_halt.webp"
level_crossing = "_generated/railway_level_crossing.webp"
station = "_generated/railway_station.webp"
subway_entrance = "_generated/railway_subway_entrance.webp"
tram_level_crossing = "_generated/railway_level_crossing.webp"
tram_stop = "_generated/railway_subway_entrance.webp"

["railway.way"]
light_rail = "_generated/railway_light_rail.webp"
rail = "_generated/railway_rail.webp"
subway = "_generated/railway_subway.webp"
tram = "_generated/railway_tram.webp"

["restriction.relation"]
"*" = "_generated/iD/restriction.webp"
no_left_turn = "_generated/iD/restriction-no-left-turn.webp"
no_right_turn = "_generated/iD/restriction-no-right-turn.webp"
no_straight_on = "_generated/iD/restriction-no-straight-on.webp"
no_u_turn = "_generated/iD/restriction-no-u-turn.webp"
only_left_turn = "_generated/iD/restriction-only-left-turn.webp"
only_right_turn = "_generated/iD/restriction-only-right-turn.webp"
only_straight_on = "_generated/iD/restriction-only-straight-on.webp"
only_u_turn = "_generated/iD/restriction-only-u-turn.webp"

[route]
detour = "_generated/iD/route-detour.webp"

[shop]
"*" = "_generated/shop_convenience.webp"
alcohol = "_generated/shop_alcohol2.webp"
anime = "_generated/shop_anime.webp"
bakery = "_generated/shop_bakery2.webp"
beauty = "_generated/shop_beauty.webp"
bicycle = "_generated/shop_bicycle.webp"
books = "_generated/shop_books2.webp"
boutique = "_generated/shop_clothes2.webp"
butcher = "_generated/shop_butcher.webp"
camera = "_generated/shop_photo.webp"
car = "_generated/shop_car.webp"
car_parts = "_generated/shop_car_parts.webp"
car_repair = "_generated/shop_car_repair.webp"
chocolate = "_generated/shop_confectionery.webp"
clothes = "_generated/shop_clothes2.webp"
computer = "_generated/shop_computer.webp"
confectionery = "_generated/shop_confectionery.webp"
convenience = "_generated/shop_convenience.webp"
copyshop = "_generated/shop_copyshop.webp"
department_store = "_generated/shop_department_store.webp"
doityourself = "_generated/shop_doityourself2.webp"
e-cigarette = "_generated/shop_tobacco.webp"
electronics = "_generated/shop_electronics.webp"
erotic = "_generated/shop_erotic.webp"
estate_agent = "_generated/shop_estate_agent2.webp"
farm = "_generated/shop_greengrocer.webp"
fishing = "_generated/shop_fishing.webp"
florist = "_generated/shop_florist2.webp"
furniture = "_generated/shop_furniture.webp"
garden_centre = "_generated/shop_garden_centre.webp"
gift = "_generated/shop_gift.webp"
greengrocer = "_generated/shop_greengrocer.webp"
hairdresser = "_generated/shop_hairdresser.webp"
hairdresser_supply = "_generated/shop_hairdresser.webp"
hardware = "_generated/shop_doityourself2.webp"
health_food = "_generated/shop_greengrocer.webp"
hearing_aids = "_generated/shop_hearing_aids.webp"
hifi = "_generated/shop_hifi.webp"
interior_decoration = "_generated/shop_furniture.webp"
jewelry = "_generated/shop_jewelry2.webp"
kiosk = "_generated/shop_kiosk.webp"
laundry = "_generated/shop_laundry.webp"
mall = "_generated/shop_department_store.webp"
mobile_phone = "_generated/shop_mobile_phone2.webp"
motorcycle = "_generated/shop_motorcycle2.webp"
music = "_generated/shop_music2.webp"
newsagent = "_generated/shop_newsagent.webp"
optician = "_generated/shop_optician2.webp"
pastry = "_generated/shop_confectionery.webp"
pet = "_generated/shop_pet2.webp"
photo = "_generated/shop_photo.webp"
seafood = "_generated/shop_seafood.webp"
shoes = "_generated/shop_shoes2.webp"
supermarket = "_generated/shop_supermarket.webp"
tobacco = "_generated/shop_tobacco.webp"
toys = "_generated/shop_toys.webp"
wine = "_generated/shop_alcohol2.webp"

[tourism]
alpine_hut = "_generated/tourism_alpine_hut.webp"
artwork = "_generated/tourism_artwork.webp"
attraction = "_generated/tourism_attraction.webp"
camp_site = "_generated/tourism_camp_site.webp"
caravan_site = "_generated/tourism_caravan_site2.webp"
chalet = "_generated/tourism_chalet.webp"
gallery = "_generated/tourism_gallery.webp"
hostel = "_generated/tourism_hostel2.webp"
hotel = "_generated/tourism_hotel2.webp"
information = "_generated/tourism_information.webp"
motel = "_generated/tourism_motel2.webp"
museum = "_generated/tourism_museum2.webp"
picnic_site = "_generated/tourism_picnic_site2.webp"
theme_park = "_generated/tourism_theme_park.webp"
viewpoint = "_generated/tourism_viewpoint.webp"
wilderness_hut = "_generated/tourism_wilderness_hut.webp"
zoo = "_generated/tourism_zoo.webp"

[traffic_calming]
bump = "_generated/traffic_calming_bump.webp"
cushion = "_generated/traffic_calming_bump.webp"
hump = "_generated/traffic_calming_bump.webp"
table = "_generated/traffic_calming_bump.webp"

["type.relation"]
multipolygon = "_generated/iD/multipolygon.webp"
network = "_generated/iD/relation.webp"
route = "_generated/iD/route.webp"
route_master = "_generated/iD/route-master.webp"

["water.way"]
"*" = "_generated/waterway_lake.webp"

[waterway]
dam = "_generated/waterway_dam.webp"
weir = "_generated/waterway_weir.webp"

["waterway.way"]
"*" = "_generated/waterway_lake.webp"
