allowed_tags = [
  "a",
  "abbr",
  "acronym",
  "address",
  "aside",
  "audio",
  "b",
  "bdi",
  "bdo",
  "blockquote",
  "br",
  "caption",
  "center",
  "cite",
  "code",
  "col",
  "colgroup",
  "data",
  "dd",
  "del",
  "details",
  "dfn",
  "div",
  "dl",
  "dt",
  "em",
  "figcaption",
  "figure",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "hgroup",
  "hr",
  "i",
  "img",
  "ins",
  "kbd",
  "li",
  "mark",
  "ol",
  "p",
  "picture",
  "pre",
  "q",
  "rp",
  "rt",
  "ruby",
  "s",
  "samp",
  "section",
  "small",
  "source",
  "span",
  "strike",
  "strong",
  "sub",
  "summary",
  "sup",
  "table",
  "tbody",
  "td",
  "tfoot",
  "th",
  "thead",
  "time",
  "title",
  "tr",
  "track",
  "u",
  "ul",
  "var",
  "video",
  "wbr",
]

[allowed_attributes]
"*" = ["dir", "hidden", "id", "lang", "tabindex", "title", "translate"]
a = ["href", "hreflang", "referrerpolicy", "rel", "type"]
audio = ["controls", "loop", "muted", "src"]
blockquote = ["cite"]
col = ["span"]
colgroup = ["span"]
data = ["value"]
del = ["cite", "datetime"]
details = ["open"]
img = ["alt", "decoding", "fetchpriority", "loading", "src"]
ins = ["cite", "datetime"]
li = ["value"]
ol = ["reversed", "start", "type"]
q = ["cite"]
source = ["sizes", "src", "srcset", "type"]
td = ["colspan", "headers", "rowspan"]
th = ["abbr", "colspan", "headers", "rowspan", "scope"]
time = ["datetime", "pubdate"]
track = ["default", "kind", "label", "src", "srclang"]
video = ["controls", "loop", "muted", "poster", "src"]
